// Code generated by Thrift Compiler (0.15.0). DO NOT EDIT.

package content_thrift

import (
	"bytes"
	"context"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/ymetas/insight/gen-go/thrift/content_thrift/content"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = content.GoUnusedProtection__

func init() {
}

