// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/admin.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetContentParam struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentParam) Reset()         { *m = GetContentParam{} }
func (m *GetContentParam) String() string { return proto.CompactTextString(m) }
func (*GetContentParam) ProtoMessage()    {}
func (*GetContentParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{0}
}

func (m *GetContentParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentParam.Unmarshal(m, b)
}
func (m *GetContentParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentParam.Marshal(b, m, deterministic)
}
func (m *GetContentParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentParam.Merge(m, src)
}
func (m *GetContentParam) XXX_Size() int {
	return xxx_messageInfo_GetContentParam.Size(m)
}
func (m *GetContentParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentParam proto.InternalMessageInfo

func (m *GetContentParam) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetContentResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentResponse) Reset()         { *m = GetContentResponse{} }
func (m *GetContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetContentResponse) ProtoMessage()    {}
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{1}
}

func (m *GetContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentResponse.Unmarshal(m, b)
}
func (m *GetContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentResponse.Marshal(b, m, deterministic)
}
func (m *GetContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentResponse.Merge(m, src)
}
func (m *GetContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetContentResponse.Size(m)
}
func (m *GetContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentResponse proto.InternalMessageInfo

func (m *GetContentResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetContentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetContentResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GetContentResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetContentResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetContentParam)(nil), "admin.GetContentParam")
	proto.RegisterType((*GetContentResponse)(nil), "admin.GetContentResponse")
}

func init() { proto.RegisterFile("proto/admin.proto", fileDescriptor_92c9b71229522f37) }

var fileDescriptor_92c9b71229522f37 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x25, 0x45,
	0x2e, 0x7e, 0xf7, 0xd4, 0x12, 0xe7, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x92, 0x80, 0xc4, 0xa2, 0xc4,
	0x5c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xa6, 0xcc,
	0x14, 0xa5, 0x09, 0x8c, 0x5c, 0x42, 0x08, 0x35, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0xe8, 0xca, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0x64, 0x88, 0x36, 0x09, 0x66, 0xb0, 0x30, 0x8c, 0x2b,
	0x24, 0xcb, 0xc5, 0x55, 0x5a, 0x90, 0x92, 0x58, 0x92, 0x9a, 0x12, 0x9f, 0x58, 0x22, 0xc1, 0x02,
	0x96, 0xe4, 0x84, 0x8a, 0x38, 0x82, 0xa5, 0x93, 0x8b, 0x52, 0x61, 0xd2, 0xac, 0x10, 0x69, 0xa8,
	0x88, 0x63, 0x89, 0x51, 0x18, 0x17, 0x8f, 0x23, 0xc8, 0xf9, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9,
	0xa9, 0x42, 0x6e, 0x5c, 0xfc, 0x4e, 0x89, 0x25, 0xc9, 0x19, 0x08, 0x67, 0x0a, 0x89, 0xe9, 0x41,
	0x7c, 0x8b, 0xe6, 0x3b, 0x29, 0x49, 0x0c, 0x71, 0x98, 0x8f, 0x94, 0x18, 0x9c, 0x38, 0xa2, 0xd8,
	0x20, 0x81, 0x94, 0xc4, 0x06, 0x0e, 0x25, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x91,
	0x3f, 0x48, 0x3a, 0x01, 0x00, 0x00,
}
